name: pyp_platform
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.3
  location: ^5.0.0
  http: ^1.4.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  geocoding: ^2.1.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  image_picker: ^1.0.3
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  file_picker: ^10.1.9
  provider: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - config.env
    - assets/images/PYP.png
    - assets/images/client.jpg
    - assets/images/profesional.jpg
      
